version: '12.8'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "12000:12000"
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=12000
      - AUTH_SERVICE_URL=http://auth-service:12004
      - USER_SERVICE_URL=http://user-service:12001
      - PRODUCT_SERVICE_URL=http://product-service:12002
      - ORDER_SERVICE_URL=http://order-service:12003
    depends_on:
      - auth-service
      - user-service
      - product-service
      - order-service
    networks:
      - microservice-network

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "12004:12004"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_PORT=12004
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    networks:
      - microservice-network

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "12001:12001"
    environment:
      - NODE_ENV=production
      - USER_SERVICE_PORT=12001
    networks:
      - microservice-network

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    ports:
      - "12002:12002"
    environment:
      - NODE_ENV=production
      - PRODUCT_SERVICE_PORT=12002
    networks:
      - microservice-network

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "12003:12003"
    environment:
      - NODE_ENV=production
      - ORDER_SERVICE_PORT=12003
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
