version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservice-network

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - USER_SERVICE_PORT=3001
    networks:
      - microservice-network

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PRODUCT_SERVICE_PORT=3002
    networks:
      - microservice-network

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - ORDER_SERVICE_PORT=3003
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
