version: "3.9"
services:
  gateway:
    build: ./gateway
    ports:
      - "12000:12000"
    environment:
      - AUTH_SERVICE_URL=http://localhost:12004
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - "12004:12004"
    env_file:
      - .env

networks:
  default:
    driver: bridge
